services:
  my-app:
    image: belalelnady/solution-plus
    container_name: u-container 
    environment:
      - APP_ENV=${APP_ENV}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - PORT=${PORT}
    ports:
      - "4040:${PORT}"
    networks:
      - app-network
    depends_on:
      - mysql-db

  mysql-db:
    image: mydb
    container_name: mysql-db
    restart: always
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql
  

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
